"""
Step 3: PRESCRIBE - Generate corrected prompt based on diagnosis.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from config import settings
from models import FailureDiagnosis, FailureType, PromptFix

PROMPTS_DIR = Path(__file__).parent.parent / "prompts"

try:
    from google import genai
    from google.genai import types
except Exception:  # pragma: no cover
    genai = None
    types = None


class Surgeon:
    """Generates prompt fixes using Gemini or deterministic rules."""

    def __init__(self):
        self.client = None
        if genai and settings.GEMINI_API_KEY and settings.GEMINI_API_KEY != "your_gemini_api_key_here":
            self.client = genai.Client(api_key=settings.GEMINI_API_KEY)

    async def prescribe(self, diagnosis: FailureDiagnosis) -> Optional[PromptFix]:
        print("[PRESCRIBE] Generating fix...")

        try:
            from agent.deployer import get_current_prompt
            current_prompt = get_current_prompt().get("template") or (PROMPTS_DIR / "flawed_v1.txt").read_text(encoding="utf-8")
        except Exception:
            current_prompt = "You are a lead routing agent. Route leads to SMB_SDR, MM_REP, or ENT_AE."

        if diagnosis.failure_type == FailureType.BOUNDARY_AMBIGUITY:
            try:
                fixed = (PROMPTS_DIR / "fixed_v2.txt").read_text(encoding="utf-8")
                fix = PromptFix(
                    new_prompt=fixed,
                    explanation="Changed ambiguous exclusive boundaries into explicit inclusive rules.",
                    boundary_fixes=[
                        "under 50 -> 50 or fewer",
                        "over 1000 -> 1000 or more",
                        "everything else -> between 51 and 999",
                    ],
                    old_prompt=current_prompt,
                )
                print(f"  Fix: {fix.explanation}")
                return fix
            except Exception as e:
                print(f"  [ERROR] Failed to read fixed_v2.txt: {e}")

        if diagnosis.failure_type == FailureType.OUTPUT_FORMAT_VIOLATION:
            new_prompt = current_prompt.rstrip() + """

Output format rules:
- Output ONLY a valid JSON object with this exact shape: {"route":"SMB_SDR|MM_REP|ENT_AE"}
- Do not include prose, markdown, explanations, or extra keys."""
            fix = PromptFix(
                new_prompt=new_prompt,
                explanation="Added a strict JSON-only response contract so downstream systems can parse the route reliably.",
                boundary_fixes=[
                    "plain route string -> JSON object",
                    "freeform response -> parseable {\"route\":\"...\"} contract",
                ],
                old_prompt=current_prompt,
            )
            print(f"  Fix: {fix.explanation}")
            return fix

        if diagnosis.failure_type == FailureType.TOOL_MISUSE:
            new_prompt = current_prompt.rstrip() + """

Tool-use rules:
- If company_size is 0, missing, or unknown, do not guess a route.
- Output ONLY CRM_LOOKUP so the CRM enrichment tool can resolve the lead before routing."""
            fix = PromptFix(
                new_prompt=new_prompt,
                explanation="Added a tool-use guardrail so incomplete leads are sent to CRM_LOOKUP instead of being guessed.",
                boundary_fixes=[
                    "unknown company size -> CRM_LOOKUP",
                    "guessing with incomplete data -> enrichment handoff",
                ],
                old_prompt=current_prompt,
            )
            print(f"  Fix: {fix.explanation}")
            return fix

        if self.client:
            return await self._prescribe_with_gemini(diagnosis, current_prompt)
        return None

    async def _prescribe_with_gemini(self, diagnosis: FailureDiagnosis, current_prompt: str) -> Optional[PromptFix]:
        prompt = f"""Fix this prompt.

CURRENT PROMPT:
{current_prompt}

DIAGNOSIS:
{diagnosis.model_dump_json()}

Return JSON with new_prompt, explanation, boundary_fixes.
"""
        response = self.client.models.generate_content(
            model=settings.GEMINI_MODEL_PRO,
            contents=prompt,
            config=types.GenerateContentConfig(response_mime_type="application/json"),
        )
        raw = json.loads(response.text)
        new_prompt = raw["new_prompt"]
        if not self._validate_safety(new_prompt):
            print("  [SAFETY CHECK FAILED]")
            return None
        return PromptFix(
            new_prompt=new_prompt,
            explanation=raw.get("explanation", "Generated by Gemini"),
            boundary_fixes=raw.get("boundary_fixes", []),
            old_prompt=current_prompt,
        )

    def _validate_safety(self, new_prompt: str) -> bool:
        forbidden = ["ignore previous", "disregard safety", "no restrictions", "bypass"]
        return not any(phrase in new_prompt.lower() for phrase in forbidden)
